# All values in no of frames
BACKGROUND_COLOR: white
FRAME_RATE: 60
NO_GO_TRIALS_TRAINING: 6
NO_GO2_TRIALS_TRAINING: 2
NO_NO_GO_TRIALS_TRAINING: 2
NO_GO_TRIALS_EXPERIMENT: 12
NO_GO2_TRIALS_EXPERIMENT: 4
NO_NO_GO_TRIALS_EXPERIMENT: 4
STIM_DURATION_IN_FRAMES: 120
FRAMES_BETWEEN_STIMS: 27
STIM_SIZE: 500
REACTION_KEYS: ['space']



